### ISSUE TITLE
Calendar events list text color and spacing

### ISSUE THREAD

**Issue by kshia** [YaleSTC/YalePublic-android#145]
Change text color and spacing for list of events shown below the calendar in "Month" tab to grey on black to match the rest of the app. Also in "List" tab.
![screenshot_20161216-163532](https://cloud.githubusercontent.com/assets/16885697/21279772/0199ba58-c3b0-11e6-9b03-f87069f2ca0f.png)

![screenshot_20161216-163539](https://cloud.githubusercontent.com/assets/16885697/21279784/0efdba82-c3b0-11e6-8bef-0506b256727b.png)

**Comment by stswidwinski** [comment]
Colors fixed in the next commit. Please see screens below.

NOTE: This is not a good fix and we will be using "theme" building the new app. This is just to keep the current app afloat while we build the new one.

![device-2016-12-19-081843](https://cloud.githubusercontent.com/assets/17051700/21314227/db3efc86-c5c3-11e6-99d7-52ba130de4ae.png)
![device-2016-12-19-081904](https://cloud.githubusercontent.com/assets/17051700/21314228/db4011f2-c5c3-11e6-8c3b-d7aed8460616.png)
