### ISSUE TITLE
Stop doing SQL query each time MainActivity is shown

### ISSUE THREAD

**Issue by jasonkliu** [YaleSTC/YalePublic-android#55]
Preferably set hidden preference for last downloaded data to increase speed of application

**Comment by Ebstein** [comment]
Weeeell, wouldn't agree with this. the hidden preference already does this, but it is not optimal not to check if anything in the interval <oldest_cached_events, newest_cached_events> is in cache. There might be a problem with internet so that events for a given month are not downloaded and this will detect the problem. The SQL query is super fast as well, so even if we want to change this, it is of low priority.

**Comment by jasonkliu** [comment]
Well, at least a dialog shouldn't pop up each time (it's noticeable)

**Comment by Ebstein** [comment]
That's a quick-fix. will do some time down the line!

**Comment by Ebstein** [comment]
done. look at the pull req.

**Comment by jasonkliu** [comment]
#107 finishes this.
